// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using VortexFit.Data;

#nullable disable

namespace VortexFit.Migrations
{
    [DbContext(typeof(VortexFitDbContext))]
    partial class VortexFitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VortexFit.Models.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ASISTENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHA")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<int>("IdSocio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SOCIO");

                    b.Property<string>("NombreClase")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOMBRE_CLASE");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdSocio");

                    b.ToTable("ASISTENCIAS");
                });

            modelBuilder.Entity("VortexFit.Models.Noticia", b =>
                {
                    b.Property<int>("IdNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_NOTICIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNoticia"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(true)
                        .HasColumnName("ACTIVO");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CATEGORIA");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONTENIDO");

                    b.Property<DateTime>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHA_PUBLICACION")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)")
                        .HasColumnName("RESUMEN");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TITULO");

                    b.HasKey("IdNoticia");

                    b.ToTable("NOTICIAS");
                });

            modelBuilder.Entity("VortexFit.Models.PushSuscripcion", b =>
                {
                    b.Property<int>("IdSuscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SUSCRIPCION");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSuscripcion"));

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("AUTH_KEY");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ENDPOINT");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHA_REGISTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<int>("IdSocio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SOCIO");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("P256DH");

                    b.HasKey("IdSuscripcion");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("UQ_PUSH_ENDPOINT");

                    b.HasIndex("IdSocio");

                    b.ToTable("PUSH_SUSCRIPCIONES");
                });

            modelBuilder.Entity("VortexFit.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESERVA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DIA");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("Confirmada")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("FechaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHA_RESERVA")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("HORA");

                    b.Property<int>("IdSocio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SOCIO");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("INSTRUCTOR");

                    b.Property<string>("NombreClase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOMBRE_CLASE");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdSocio");

                    b.ToTable("RESERVAS");
                });

            modelBuilder.Entity("VortexFit.Models.Socio", b =>
                {
                    b.Property<int>("IdSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SOCIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSocio"));

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CODIGO_ACCESO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHA_REGISTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHA_VENCIMIENTO");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOMBRE_COMPLETO");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PLAN");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasDefaultValue("Usuario")
                        .HasColumnName("ROL");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("TELEFONO");

                    b.HasKey("IdSocio");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_SOCIOS_EMAIL");

                    b.ToTable("SOCIOS");
                });

            modelBuilder.Entity("VortexFit.Models.Asistencia", b =>
                {
                    b.HasOne("VortexFit.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("VortexFit.Models.PushSuscripcion", b =>
                {
                    b.HasOne("VortexFit.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("VortexFit.Models.Reserva", b =>
                {
                    b.HasOne("VortexFit.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });
#pragma warning restore 612, 618
        }
    }
}
